### ISSUE TITLE
Should I ignore the build binary?

### ISSUE THREAD

**Issue by mtilda** [mxkay/techtrans-bot#15]
`go build` generates a binary build of the program. To be safe, I am assuming this file could contain secrets/environmental variables (stored in an ignored `.json` file) that I do not want to expose, so I am ignoring it.

I notice [GitHub's standard gitignore template for Go](https://github.com/github/gitignore/blob/master/Go.gitignore) does not ignore this binary.

I ignored it by adding the following lines to my gitignore:
```
# Ignore all
*

# Unignore all with extensions and directories
!*.*
!*/
```

Is this unnecessary? Is there a better practice?

**Comment by nicholascassidy** [comment]
In general, the best practice is to abstract out secrets and environmental config variables, often times to a .ENV file that's hoisted at runtime. The reason being, as you mentioned, is to avoid exposing those details, but also to make it easier to assign variables during deployment to a variety of environments.

Being that you can't use third party plugins for this assignment, don't worry about using .ENV files as they can be a pain to manually parse. Using a standard JSON file is significantly easier to open and parse - so feel free to go that route in order to maintain the separation, and do ignore that file as you mentioned.

**Comment by mtilda** [comment]
Thank you kindly! That all makes sense and echoes what most of my research has told me so far.

I have it working with the `.json` file, so I will keep it as is for now. But I will make a note to switch to `.env` later on for deployment.
